/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiRobotsRouteImport } from './routes/api/robots'
import { Route as ApiOgImageRouteImport } from './routes/api/og-image'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAiWriterRouteImport } from './routes/admin/ai-writer'
import { Route as CollectionSlugRouteImport } from './routes/$collection.$slug'
import { Route as AdminEntriesIndexRouteImport } from './routes/admin/entries/index'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin/collections/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiArticleRouteImport } from './routes/api/ai/article'
import { Route as AdminEntriesNewRouteImport } from './routes/admin/entries/new'
import { Route as AdminEntriesIdRouteImport } from './routes/admin/entries/$id'
import { Route as AdminCollectionsIdRouteImport } from './routes/admin/collections/$id'
import { Route as AdminEntriesIdPreviewRouteImport } from './routes/admin/entries/$id.preview'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsRoute = ApiRobotsRouteImport.update({
  id: '/api/robots',
  path: '/api/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgImageRoute = ApiOgImageRouteImport.update({
  id: '/api/og-image',
  path: '/api/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiWriterRoute = AdminAiWriterRouteImport.update({
  id: '/ai-writer',
  path: '/ai-writer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/$collection/$slug',
  path: '/$collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntriesIndexRoute = AdminEntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiArticleRoute = ApiAiArticleRouteImport.update({
  id: '/api/ai/article',
  path: '/api/ai/article',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntriesNewRoute = AdminEntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEntriesIdRoute = AdminEntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectionsIdRoute = AdminCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEntriesIdPreviewRoute = AdminEntriesIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminEntriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$collection/$slug': typeof CollectionSlugRoute
  '/admin/ai-writer': typeof AdminAiWriterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/entries/$id': typeof AdminEntriesIdRouteWithChildren
  '/admin/entries/new': typeof AdminEntriesNewRoute
  '/api/ai/article': typeof ApiAiArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/entries/': typeof AdminEntriesIndexRoute
  '/admin/entries/$id/preview': typeof AdminEntriesIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$collection/$slug': typeof CollectionSlugRoute
  '/admin/ai-writer': typeof AdminAiWriterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/entries/$id': typeof AdminEntriesIdRouteWithChildren
  '/admin/entries/new': typeof AdminEntriesNewRoute
  '/api/ai/article': typeof ApiAiArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/entries': typeof AdminEntriesIndexRoute
  '/admin/entries/$id/preview': typeof AdminEntriesIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$collection/$slug': typeof CollectionSlugRoute
  '/admin/ai-writer': typeof AdminAiWriterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/entries/$id': typeof AdminEntriesIdRouteWithChildren
  '/admin/entries/new': typeof AdminEntriesNewRoute
  '/api/ai/article': typeof ApiAiArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/entries/': typeof AdminEntriesIndexRoute
  '/admin/entries/$id/preview': typeof AdminEntriesIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/mcp'
    | '/$collection/$slug'
    | '/admin/ai-writer'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/settings'
    | '/api/og-image'
    | '/api/robots'
    | '/api/sitemap'
    | '/api/upload'
    | '/admin/'
    | '/admin/collections/$id'
    | '/admin/entries/$id'
    | '/admin/entries/new'
    | '/api/ai/article'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/collections/'
    | '/admin/entries/'
    | '/admin/entries/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/mcp'
    | '/$collection/$slug'
    | '/admin/ai-writer'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/settings'
    | '/api/og-image'
    | '/api/robots'
    | '/api/sitemap'
    | '/api/upload'
    | '/admin'
    | '/admin/collections/$id'
    | '/admin/entries/$id'
    | '/admin/entries/new'
    | '/api/ai/article'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/collections'
    | '/admin/entries'
    | '/admin/entries/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/mcp'
    | '/$collection/$slug'
    | '/admin/ai-writer'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/settings'
    | '/api/og-image'
    | '/api/robots'
    | '/api/sitemap'
    | '/api/upload'
    | '/admin/'
    | '/admin/collections/$id'
    | '/admin/entries/$id'
    | '/admin/entries/new'
    | '/api/ai/article'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/collections/'
    | '/admin/entries/'
    | '/admin/entries/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  ApiOgImageRoute: typeof ApiOgImageRoute
  ApiRobotsRoute: typeof ApiRobotsRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAiArticleRoute: typeof ApiAiArticleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots': {
      id: '/api/robots'
      path: '/api/robots'
      fullPath: '/api/robots'
      preLoaderRoute: typeof ApiRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og-image': {
      id: '/api/og-image'
      path: '/api/og-image'
      fullPath: '/api/og-image'
      preLoaderRoute: typeof ApiOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-writer': {
      id: '/admin/ai-writer'
      path: '/ai-writer'
      fullPath: '/admin/ai-writer'
      preLoaderRoute: typeof AdminAiWriterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$collection/$slug': {
      id: '/$collection/$slug'
      path: '/$collection/$slug'
      fullPath: '/$collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entries/': {
      id: '/admin/entries/'
      path: '/entries'
      fullPath: '/admin/entries/'
      preLoaderRoute: typeof AdminEntriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/article': {
      id: '/api/ai/article'
      path: '/api/ai/article'
      fullPath: '/api/ai/article'
      preLoaderRoute: typeof ApiAiArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entries/new': {
      id: '/admin/entries/new'
      path: '/entries/new'
      fullPath: '/admin/entries/new'
      preLoaderRoute: typeof AdminEntriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/entries/$id': {
      id: '/admin/entries/$id'
      path: '/entries/$id'
      fullPath: '/admin/entries/$id'
      preLoaderRoute: typeof AdminEntriesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collections/$id': {
      id: '/admin/collections/$id'
      path: '/collections/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AdminCollectionsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/entries/$id/preview': {
      id: '/admin/entries/$id/preview'
      path: '/preview'
      fullPath: '/admin/entries/$id/preview'
      preLoaderRoute: typeof AdminEntriesIdPreviewRouteImport
      parentRoute: typeof AdminEntriesIdRoute
    }
  }
}

interface AdminEntriesIdRouteChildren {
  AdminEntriesIdPreviewRoute: typeof AdminEntriesIdPreviewRoute
}

const AdminEntriesIdRouteChildren: AdminEntriesIdRouteChildren = {
  AdminEntriesIdPreviewRoute: AdminEntriesIdPreviewRoute,
}

const AdminEntriesIdRouteWithChildren = AdminEntriesIdRoute._addFileChildren(
  AdminEntriesIdRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAiWriterRoute: typeof AdminAiWriterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsIdRoute: typeof AdminCollectionsIdRoute
  AdminEntriesIdRoute: typeof AdminEntriesIdRouteWithChildren
  AdminEntriesNewRoute: typeof AdminEntriesNewRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminEntriesIndexRoute: typeof AdminEntriesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiWriterRoute: AdminAiWriterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsIdRoute: AdminCollectionsIdRoute,
  AdminEntriesIdRoute: AdminEntriesIdRouteWithChildren,
  AdminEntriesNewRoute: AdminEntriesNewRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminEntriesIndexRoute: AdminEntriesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  ApiOgImageRoute: ApiOgImageRoute,
  ApiRobotsRoute: ApiRobotsRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAiArticleRoute: ApiAiArticleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
