/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiRobotsRouteImport } from './routes/api/robots'
import { Route as ApiOgImageRouteImport } from './routes/api/og-image'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as CollectionSlugRouteImport } from './routes/$collection.$slug'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiArticleRouteImport } from './routes/api/ai/article'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsRoute = ApiRobotsRouteImport.update({
  id: '/api/robots',
  path: '/api/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgImageRoute = ApiOgImageRouteImport.update({
  id: '/api/og-image',
  path: '/api/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/$collection/$slug',
  path: '/$collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiArticleRoute = ApiAiArticleRouteImport.update({
  id: '/api/ai/article',
  path: '/api/ai/article',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$collection/$slug': typeof CollectionSlugRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/ai/article': typeof ApiAiArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$collection/$slug': typeof CollectionSlugRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/ai/article': typeof ApiAiArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/$collection/$slug': typeof CollectionSlugRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/ai/article': typeof ApiAiArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/mcp'
    | '/$collection/$slug'
    | '/admin/$'
    | '/api/og-image'
    | '/api/robots'
    | '/api/sitemap'
    | '/api/upload'
    | '/api/ai/article'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/mcp'
    | '/$collection/$slug'
    | '/admin/$'
    | '/api/og-image'
    | '/api/robots'
    | '/api/sitemap'
    | '/api/upload'
    | '/api/ai/article'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/mcp'
    | '/$collection/$slug'
    | '/admin/$'
    | '/api/og-image'
    | '/api/robots'
    | '/api/sitemap'
    | '/api/upload'
    | '/api/ai/article'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  ApiOgImageRoute: typeof ApiOgImageRoute
  ApiRobotsRoute: typeof ApiRobotsRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAiArticleRoute: typeof ApiAiArticleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots': {
      id: '/api/robots'
      path: '/api/robots'
      fullPath: '/api/robots'
      preLoaderRoute: typeof ApiRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og-image': {
      id: '/api/og-image'
      path: '/api/og-image'
      fullPath: '/api/og-image'
      preLoaderRoute: typeof ApiOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$collection/$slug': {
      id: '/$collection/$slug'
      path: '/$collection/$slug'
      fullPath: '/$collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/article': {
      id: '/api/ai/article'
      path: '/api/ai/article'
      fullPath: '/api/ai/article'
      preLoaderRoute: typeof ApiAiArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  ApiOgImageRoute: ApiOgImageRoute,
  ApiRobotsRoute: ApiRobotsRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAiArticleRoute: ApiAiArticleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
